
# This file provides instructions for packaging.

@base <http://purl.org/NET/cpan-uri/dist/RDF-Generator-Void/> .
@prefix :  <http://ontologi.es/doap-deps#> .

<project>
    :test-requirement [ :on "Test::More 0.88" ];
    :test-requirement [ :on "Test::RDF 1.10" ];
    :test-requirement [ :on "FindBin" ];    
    :test-requirement [ :on "File::Temp" ];
    :runtime-recommendation [ :on "App::perlrdf 0.004" ];
    :runtime-requirement [ :on "RDF::Trine" ];
    :runtime-requirement [ :on  "URI" ];
    :runtime-requirement [ :on  "Data::UUID"];
    :runtime-requirement [ :on  "Moose" ];
    :runtime-requirement [ :on  "aliased" ] .


