
# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .
@base <http://purl.org/NET/cpan-uri/dist/RDF-Generator-Void/> .

<project>
    :all_from <project#main> ;
    :readme_from <project#main> ;
    :test_requires "" ;
    :requires "Scalar::Util", "Test::More", "Test::Builder::Module", "RDF::Trine 0.134" .

<project#main> <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/Test/RDF.pm" .
